#!/usr/bin/bash

INSTALL_PATH="/usr/local/bin/docker-compose"
TEMP="/tmp/docker-tmp"
OS=$(uname -s)
ARCH=$(uname -m)

function usage {
    echo "$0 [version_to_install]"
}

function command_check {
    if [ $? -ne 0 ]; then
        MSG="ERR"
        COLOR="\e[91m"
        rm -f $TEMP
    else
        MSG="OK"
        COLOR="\e[92m"
    fi

    echo -n "* $2 "
    for i in $(seq 1 $3); do
        echo -n "."
    done
    echo -en " $COLOR[ $MSG ]\e[39m"
    echo ""

    if [ $MSG = "ERR" ]; then
        rm -f $TEMP
        exit 1
    fi
}

function latest {
    SED=$(which sed 2> /dev/null)
    if [ -z $SED ]; then
        echo "Error, sed not found"
        echo "Please install sed and try again"
    fi

    echo -e "\e[93m"
    echo "NOTICE: No version selected, checking for the latest release"
    echo -e "\e[39m"

    LATEST_RELEASE="https://github.com/docker/compose/releases/latest"
    TMP_URL=$($CURL $LATEST_RELEASE  2> /dev/null | cut -d '"' -f2)
    URL=$($SED "s/tag/download/g" <<< $TMP_URL)
}

CURL=$(which curl 2> /dev/null)
if [ -z $CURL ]; then
    echo "Error, curl not found"
    echo "Please install curl and try again"
fi

# If not version provided we check
# for latest docker-compose
if [ -z $1 ]; then
    latest
else
    URL="https://github.com/docker/compose/releases/download/$1"
fi

URL=$URL"/docker-compose-${OS}-${ARCH}"
echo "Downloading from: $URL"

$CURL --progress-bar -L "$URL" > $TEMP;
command_check "curl" "Download" 15
chmod +x $TEMP
command_check "chmod" "Setting permissions" 4
sudo mv $TEMP $INSTALL_PATH
command_check "mv" "Installing" 13
